### ISSUE TITLE
Headless table fails

### ISSUE THREAD

**Issue by danielpclark** [piotrmurach/tty-table#14]
I was planning to use a one row table for the alignment I can get from using it.  But it doesn't seem to work that way.

```ruby
require 'tty-table'
# => true
TTY::Table.new ['left', 'center', 'right']
/home/danielpclark/.rvm/gems/ruby-2.4.0/gems/necromancer-0.3.0/lib/necromancer/conversion_target.rb:69: warning: constant ::Fixnum is deprecated
/home/danielpclark/.rvm/gems/ruby-2.4.0/gems/necromancer-0.3.0/lib/necromancer/conversion_target.rb:69: warning: constant ::Bignum is deprecated
NoMethodError: undefined method `zip' for nil:NilClass
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table/row.rb:78:in `initialize'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table/row.rb:14:in `new'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table/row.rb:14:in `to_row'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table.rb:466:in `block in coerce'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table.rb:466:in `map'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table.rb:466:in `coerce'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table.rb:119:in `initialize'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table.rb:95:in `new'
	from /home/danielpclark/.rvm/gems/ruby-2.4.0/gems/tty-table-0.7.0/lib/tty/table.rb:95:in `new'
	from (irb):2
	from /usr/share/rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```

I wrote the following code to solve what I was going for:
```ruby
def draw left=nil, center=nil, right=nil
  width = SUBMENUWIDTH
  str = left.to_s
  str = str + center.to_s.rjust(width/2 - str.length + center.to_s.length/2)
  str + right.to_s.rjust(width - str.length)
end 
```
The above lets me use the same method for both left and right alignment, or for centered text.  I haven't mixed the two/three yet as I've only needed one or the other.

**Comment by piotrmurach** [comment]
The library expects array of arrays as data input. For example

```ruby
table = TTY::Table.new [['left', 'center', 'right']]
puts table.render(:ascii)
```
or if you prefer more array like behaviour:
```ruby
table = TTY::Table.new
table << ['left', 'center', 'right']
puts table.render(:ascii)
```
Finally, if you want to apply alignment to all elements in each column do:
```ruby
table.render(:ascii, alignments: [:left, :center, :right])
```
