### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by nuhasha** [piotrmurach/tty-table#43]
### Describe the problem

```
node_modules/tty-table/src/format.js:172
            + Array(padBoth + 1 + padRemainder).join(" ")
              ^
RangeError: Invalid array length

  at /node_modules/tty-table/src/format.js:172:15
    at Array.map (<anonymous>)
    at module.exports.wrapCellText (/node_modules/tty-table/src/format.js:156:35)
    at module.exports.buildCell (/node_modules/tty-table/src/render.js:287:39)
    at /node_modules/tty-table/src/render.js:171:26
    at Array.map (<anonymous>)
    at module.exports.buildRow (/node_modules/tty-table/src/render.js:170:13)
    at /node_modules/tty-table/src/render.js:47:24
    at Array.map (<anonymous>)
    at module.exports.stringifyData (/node_modules/tty-table/src/render.js:46:45)

Node.js v18.17.1

```
The version of `tty-table` I use is: ` "tty-table": "^4.1.3"`

### Steps to reproduce the problem

```
Your code here to reproduce the issue
```

### Actual behaviour

What happened? This could be a description, log output, error raised etc.

### Expected behaviour

What did you expect to happen?

### Describe your environment

* OS version:
* Ruby version:
* TTY::Table version:

**Comment by piotrmurach** [comment]
@nuhasha This is the wrong project. This is a Ruby gem called `tty-table`. What you're after is this Node.js project https://github.com/tecfu/tty-table.
